name: diad
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
      - albumentations==1.3.0
      - annotator==0.14.2
      - datasets==2.14.4
      - einops==0.3.0
      - gradio==3.40.1
      - numpy==1.23.1
      - omegaconf==2.1.1
      - open_clip_torch==2.0.2
      - opencv_contrib_python==4.3.0.36
      - opencv_python==4.7.0.72
      - opencv_python_headless==4.7.0.72
      - pandas==1.3.4
      - Pillow==9.4.0
      - pytorch_lightning==1.5.0
      - safetensors==0.2.7
      - scikit_learn==1.2.2
      - scipy==1.9.1
      - scikit-image==0.20.0
      - tabulate==0.9.0
      - timm==0.6.12
      - torchmetrics==0.6.0
      - tqdm==4.65.0
      - transformers==4.19.2
      - xformers==0.0.18
      - opencv-python==4.5.1.48
      - taming-transformers
